force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>Reg-{000000}</displayFormat>
        <label>Event Registrations Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventRegistrationService.cls
public inherited sharing class EventRegistrationService {

    public static void registerEvent(Contact contact, Event__c event){
        
        List<Contact> existingContacts  = new ContactSelector().selectByEmail(contact.email);
                
        if(existingContacts != null && !existingContacts.isEmpty()){
            contact.Id = existingContacts[0].Id;
        }

        upsert contact;

        List<Event_Registration__c> existingRegistrations = new EventRegistrationSelector().selectByEventAndContact(event.Id, contact.Id);

        if(existingRegistrations == null || existingRegistrations.isEmpty()){
            Event_Registration__c registration = new Event_Registration__c(Contact__c = contact.Id, Event__c = event.Id);
            insert registration;
        }else{

            throw new EventRegisterationException(Label.Already_Registered);

        }

    }
}