force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>Reg-{000000}</displayFormat>
        <label>Event Registrations Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventRegistrationSelector.cls
public inherited sharing class EventRegistrationSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){

        return new List<Schema.SObjectField>{
            Event_Registration__c.Contact__c,
            Event_Registration__c.Event__c,
            Event_Registration__c.Name
        };

    }

    public Schema.SObjectType getSObjectType(){
        return Event_Registration__c.sObjectType;
    }

    public List<Event_Registration__c> selectByEventAndContact(Id eventId, Id contactId){

        return (List<Event_Registration__c>)Database.query(
            newQueryFactory().setCondition('Contact__c = :contactId AND Event__c = :eventId').toSOQL()
        );

    }
    
}