force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Number_of_participants_allowed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_participants_allowed__c</fullName>
    <label>Number of participants allowed</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Number_of_registrations__c.field-meta.xml
<CustomField>
    <fullName>Number_of_registrations__c</fullName>
    <label>Number of registrations</label>
    <summaryForeignKey>Event_Registration__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/EventControllerExtension.cls
public inherited sharing class EventControllerExtension {
    private final Event__c event;
    
    public String registrationMessage{get;set;}

    public String email{get;set;}
    public String firstName{get;set;}
    public String lastName{get;set;}

    
    public EventControllerExtension(ApexPages.StandardController stdController) {

        stdController.addFields(new List<String>{'Number_of_participants_allowed__c','Number_of_registrations__c'});
        this.event = (Event__c)stdController.getRecord();

    }

    public Boolean getIsRegistrationAllowed(){
        return this.event.Number_of_participants_allowed__c==null || this.event.Number_of_participants_allowed__c > this.event.Number_of_registrations__c;
    }

    public void register(){
        Contact contact = new Contact(firstName = firstName, lastName = lastName, email = email);
        if(getIsRegistrationAllowed()){

            try {
                EventRegistrationService.registerEvent(contact, event);
                registrationMessage = Label.RegistrationSuccess;
            } catch (Exception e) {
                registrationMessage = e.getMessage();
            }

        }else{
            registrationMessage = Label.Registration_Closed;
        }
    }


}